# Generated by Django 4.0.1 on 2022-02-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='static/posts'),
        ),
    ]
