# Generated by Django 4.0.1 on 2022-02-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_bio_alter_user_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dp',
            field=models.ImageField(blank=True, default='static/profile/person.svg', null=True, upload_to='static/profile'),
        ),
    ]
